const $=id=>document.getElementById(id);
const fileInput=$('fileInput'),dropzone=$('dropzone'),fileStatus=$('fileStatus'),editor=$('editor'),ctx=editor.getContext('2d'),processBtn=$('processBtn'),zipBtn=$('zipBtn'),results=$('results'),clearBtn=$('clearBtn'),progressWrap=$('progressWrap'),progressBar=$('progressBar'),progressPct=$('progressPct'),progressText=$('progressText');
let files=[],outputs=[],srcCanvas=null,frame=null,dragCorner=-1;
fileInput.onchange=()=>setFiles([...fileInput.files]);
['dragover','dragenter'].forEach(e=>dropzone.addEventListener(e,x=>{x.preventDefault();dropzone.style.borderColor='#4c7fe8'}));
['dragleave','drop'].forEach(e=>dropzone.addEventListener(e,x=>{x.preventDefault();dropzone.style.borderColor='#cbd0d8'}));
dropzone.addEventListener('drop',e=>setFiles([...e.dataTransfer.files]));
function setFiles(arr){files=arr.filter(f=>/^image\/(jpeg|png|webp)$/.test(f.type));fileStatus.textContent=files.length?`已選取 ${files.length} 張圖片`:'未選取可處理的圖片';fileStatus.classList.toggle('ok',!!files.length);if(files.length)loadFirst(files[0]);processBtn.disabled=!files.length||!frame}
function loadFirst(f){const u=URL.createObjectURL(f),im=new Image();im.onload=()=>{const max=1600,s=Math.min(1,max/im.naturalWidth);srcCanvas=document.createElement('canvas');srcCanvas.width=Math.round(im.naturalWidth*s);srcCanvas.height=Math.round(im.naturalHeight*s);srcCanvas.getContext('2d').drawImage(im,0,0,srcCanvas.width,srcCanvas.height);editor.width=srcCanvas.width;editor.height=srcCanvas.height;smartFrame();URL.revokeObjectURL(u)};im.src=u}
function smartFrame(){if(!srcCanvas)return;const w=srcCanvas.width,h=srcCanvas.height;frame={p:[{x:w*.13,y:h*.08},{x:w*.87,y:h*.08},{x:w*.87,y:h*.90},{x:w*.13,y:h*.90}]};draw()}
$('smartBtn').onclick=smartFrame;$('resetBtn').onclick=smartFrame;
function pointer(e){const r=editor.getBoundingClientRect();return{x:(e.clientX-r.left)*editor.width/r.width,y:(e.clientY-r.top)*editor.height/r.height}}
function nearCorner(p){let best=-1,bd=Math.max(36,editor.width*.035);frame.p.forEach((q,i)=>{const z=Math.hypot(p.x-q.x,p.y-q.y);if(z<bd){bd=z;best=i}});return best}
editor.addEventListener('pointerdown',e=>{const p=pointer(e);dragCorner=nearCorner(p);if(dragCorner>=0)editor.setPointerCapture(e.pointerId)});
editor.addEventListener('pointermove',e=>{if(dragCorner<0||!frame)return;const p=pointer(e),min=20;frame.p[dragCorner].x=Math.max(min,Math.min(editor.width-min,p.x));frame.p[dragCorner].y=Math.max(min,Math.min(editor.height-min,p.y));draw()});
editor.addEventListener('pointerup',()=>dragCorner=-1);
function draw(){if(!srcCanvas||!frame)return;ctx.clearRect(0,0,editor.width,editor.height);ctx.drawImage(srcCanvas,0,0);ctx.save();ctx.fillStyle='rgba(0,0,0,.22)';ctx.fillRect(0,0,editor.width,editor.height);ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.moveTo(frame.p[0].x,frame.p[0].y);frame.p.slice(1).forEach(q=>ctx.lineTo(q.x,q.y));ctx.closePath();ctx.fill();ctx.restore();ctx.save();ctx.strokeStyle='#2d72e8';ctx.lineWidth=Math.max(4,editor.width/260);ctx.beginPath();ctx.moveTo(frame.p[0].x,frame.p[0].y);frame.p.slice(1).forEach(q=>ctx.lineTo(q.x,q.y));ctx.closePath();ctx.stroke();frame.p.forEach(q=>{ctx.beginPath();ctx.fillStyle='#fff';ctx.strokeStyle='#2d72e8';ctx.lineWidth=4;ctx.arc(q.x,q.y,11,0,Math.PI*2);ctx.fill();ctx.stroke()});ctx.restore();processBtn.disabled=!files.length||!frame}
function loadImageCanvas(file,max=1800){return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{const s=Math.min(1,max/im.naturalWidth),c=document.createElement('canvas');c.width=Math.round(im.naturalWidth*s);c.height=Math.round(im.naturalHeight*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);resolve(c)};im.onerror=reject;im.src=u})}
function polygonMask(canvas,norm){const w=canvas.width,h=canvas.height,mask=new Uint8Array(w*h),p=norm.map(q=>({x:q.x*w,y:q.y*h}));const minX=Math.max(0,Math.floor(Math.min(...p.map(q=>q.x)))),maxX=Math.min(w-1,Math.ceil(Math.max(...p.map(q=>q.x)))),minY=Math.max(0,Math.floor(Math.min(...p.map(q=>q.y)))),maxY=Math.min(h-1,Math.ceil(Math.max(...p.map(q=>q.y))));function inside(x,y){let hit=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if(((a.y>y)!=(b.y>y))&&x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x)hit=!hit}return hit}for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++)if(inside(x+.5,y+.5))mask[y*w+x]=1;return{mask,minX,maxX,minY,maxY}}
function quadToNorm(){return frame.p.map(q=>({x:q.x/editor.width,y:q.y/editor.height}))}
function percentile(vals,p){if(!vals.length)return 255;vals.sort((a,b)=>a-b);return vals[Math.min(vals.length-1,Math.floor((vals.length-1)*p))]}
function colorCorrect(data,w,h,mask,opts){const out=new Uint8ClampedArray(data.length);out.set(data);let white=[];let lum=[];for(let y=0;y<h;y+=2)for(let x=0;x<w;x+=2){const k=y*w+x;if(!mask[k])continue;const i=k*4,r=data[i],g=data[i+1],b=data[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),sat=mx?((mx-mn)/mx):0,l=.2126*r+.7152*g+.0722*b;if(sat<.10&&l>150){white.push(l);if(white.length<12000)lum.push(l)}}let wp=percentile(white,.92);let scale=opts.wb?Math.min(1.18,Math.max(1,248/wp)):1;const br=opts.brightness/100,con=opts.contrast/100;for(let i=0;i<data.length;i+=4){const k=i/4;if(!mask[k]){out[i+3]=0;continue}let r=data[i]*scale,g=data[i+1]*scale,b=data[i+2]*scale;r=r+(255-r)*br;g=g+(255-g)*br;b=b+(255-b)*br;const factor=1+con;r=128+(r-128)*factor;g=128+(g-128)*factor;b=128+(b-128)*factor;out[i]=Math.max(0,Math.min(255,r));out[i+1]=Math.max(0,Math.min(255,g));out[i+2]=Math.max(0,Math.min(255,b));out[i+3]=255}return out}
async function processOne(file){const source=await loadImageCanvas(file),norm=quadToNorm(),m=polygonMask(source,norm),w=source.width,h=source.height,d=source.getContext('2d').getImageData(0,0,w,h).data;let x0=m.minX,y0=m.minY,x1=m.maxX,y1=m.maxY;const pad=.012,bw=x1-x0+1,bh=y1-y0+1;x0=Math.max(0,Math.floor(x0-bw*pad));y0=Math.max(0,Math.floor(y0-bh*pad));x1=Math.min(w-1,Math.ceil(x1+bw*pad));y1=Math.min(h-1,Math.ceil(y1+bh*pad));const cw=x1-x0+1,ch=y1-y0+1,size=+$('size').value,out=document.createElement('canvas');out.width=size;out.height=size;const c=out.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,size,size);const fit=Math.min(size*.84/cw,size*.84/ch),dw=cw*fit,dh=ch*fit,dx=(size-dw)/2,dy=(size-dh)/2;const subMask=new Uint8Array(cw*ch);const sd=new Uint8ClampedArray(cw*ch*4);for(let yy=0;yy<ch;yy++)for(let xx=0;xx<cw;xx++){const sx=x0+xx,sy=y0+yy,k=sy*w+sx,si=k*4,li=(yy*cw+xx)*4;subMask[yy*cw+xx]=m.mask[k];if(m.mask[k]){sd[li]=d[si];sd[li+1]=d[si+1];sd[li+2]=d[si+2];sd[li+3]=255}}
const corrected=colorCorrect(sd,cw,ch,subMask,{wb:$('wb').checked,brightness:+$('brightness').value,contrast:+$('contrast').value});const layer=document.createElement('canvas');layer.width=cw;layer.height=ch;layer.getContext('2d').putImageData(new ImageData(corrected,cw,ch),0,0);
if($('shadow').checked){c.save();c.globalAlpha=.13;c.filter='blur(18px)';c.fillStyle='#000';c.beginPath();c.ellipse(size/2,dy+dh*.975,dw*.27,Math.max(7,dh*.016),0,0,Math.PI*2);c.fill();c.restore()}
c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(layer,dx,dy,dw,dh);const type=$('format').value,blob=await new Promise((r,j)=>out.toBlob(b=>b?r(b):j(Error('輸出失敗')),type,type==='image/png'?undefined:.95));const ext=type==='image/png'?'png':type==='image/webp'?'webp':'jpg';return{name:file.name.replace(/\.[^.]+$/,'')+'_白底棚拍V12.'+ext,blob,url:URL.createObjectURL(blob),w:size,h:size}}
processBtn.onclick=async()=>{outputs=[];results.innerHTML='';progressWrap.classList.remove('hidden');processBtn.disabled=true;for(let i=0;i<files.length;i++){progressText.textContent=`正在處理 ${i+1}/${files.length}`;try{const o=await processOne(files[i]);outputs.push(o);render(o)}catch(e){render({name:files[i].name,error:'處理失敗：'+e.message})}const p=Math.round((i+1)/files.length*100);progressBar.style.width=p+'%';progressPct.textContent=p+'%';await new Promise(r=>setTimeout(r,10))}progressText.textContent='完成';processBtn.disabled=false;zipBtn.disabled=!outputs.length};
function render(o){const d=document.createElement('div');d.className='result';d.innerHTML=o.error?`<div class="result-name">${esc(o.name)}</div><div class="error">${esc(o.error)}</div>`:`<div class="preview-wrap"><img src="${o.url}"></div><div class="result-name">${esc(o.name)}</div><div class="result-meta">輸出 ${o.w} × ${o.h} px · ${(o.blob.size/1024).toFixed(0)} KB</div><span class="status">棚拍校正完成</span><br><a class="download" href="${o.url}" download="${esc(o.name)}">下載</a>`;results.appendChild(d)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
clearBtn.onclick=()=>{outputs.forEach(x=>x.url&&URL.revokeObjectURL(x.url));outputs=[];results.innerHTML='<div class="empty">尚無處理結果</div>';zipBtn.disabled=true};
zipBtn.onclick=async()=>{const z=await makeZip(outputs),u=URL.createObjectURL(z),a=document.createElement('a');a.href=u;a.download='商品照片校正_白底棚拍V12_全部圖片.zip';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
async function makeZip(items){const enc=new TextEncoder(),parts=[],central=[];let off=0;for(const it of items){const n=enc.encode(it.name),data=new Uint8Array(await it.blob.arrayBuffer()),crc=crc32(data),l=new Uint8Array(30+n.length+data.length),v=new DataView(l.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,n.length,true);l.set(n,30);l.set(data,30+n.length);parts.push(l);const c=new Uint8Array(46+n.length),d=new DataView(c.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint32(16,crc,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,n.length,true);d.setUint32(42,off,true);c.set(n,46);central.push(c);off+=l.length}const cs=central.reduce((s,a)=>s+a.length,0),e=new Uint8Array(22),v=new DataView(e.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,items.length,true);v.setUint16(10,items.length,true);v.setUint32(12,cs,true);v.setUint32(16,off,true);return new Blob([...parts,...central,e],{type:'application/zip'})}
function crc32(b){let t=crc32.t;if(!t){t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}crc32.t=t}let c=0xffffffff;for(const x of b)c=t[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0}
$('wb').onchange=()=>{$('wbVal').textContent=$('wb').checked?'開啟':'關閉'};
$('shadow').onchange=()=>{$('shadowVal').textContent=$('shadow').checked?'開啟':'關閉'};
$('brightness').oninput=()=>{$('brightVal').textContent='＋'+$('brightness').value};
$('contrast').oninput=()=>{$('contrastVal').textContent='＋'+$('contrast').value};
