const $=id=>document.getElementById(id);
const fileInput=$("fileInput"),dropzone=$("dropzone"),fileStatus=$("fileStatus"),editor=$("editor"),ctx=editor.getContext("2d"),processBtn=$("processBtn"),zipBtn=$("zipBtn"),results=$("results"),clearBtn=$("clearBtn"),progressWrap=$("progressWrap"),progressBar=$("progressBar"),progressPct=$("progressPct"),progressText=$("progressText");
let files=[],outputs=[],srcCanvas=null,frame=null,dragCorner=-1;

fileInput.onchange=()=>setFiles([...fileInput.files]);
["dragover","dragenter"].forEach(e=>dropzone.addEventListener(e,x=>{x.preventDefault();dropzone.style.borderColor="#4c7fe8"}));
["dragleave","drop"].forEach(e=>dropzone.addEventListener(e,x=>{x.preventDefault();dropzone.style.borderColor="#cbd0d8"}));
dropzone.addEventListener("drop",e=>setFiles([...e.dataTransfer.files]));
function setFiles(arr){files=arr.filter(f=>/^image\/(jpeg|png|webp)$/.test(f.type));fileStatus.textContent=files.length?`已選取 ${files.length} 張圖片`:"未選取可處理的圖片";fileStatus.classList.toggle("ok",!!files.length);processBtn.disabled=!files.length||!frame;if(files.length)loadFirst(files[0])}
function loadFirst(f){const u=URL.createObjectURL(f),im=new Image();im.onload=()=>{const max=1500,s=Math.min(1,max/im.naturalWidth);srcCanvas=document.createElement("canvas");srcCanvas.width=Math.round(im.naturalWidth*s);srcCanvas.height=Math.round(im.naturalHeight*s);srcCanvas.getContext("2d").drawImage(im,0,0,srcCanvas.width,srcCanvas.height);editor.width=srcCanvas.width;editor.height=srcCanvas.height;smartFrame();URL.revokeObjectURL(u)};im.src=u}

// V11 的智慧框選只負責找「大致的商品外框」，不參與去背。
function smartFrame(){if(!srcCanvas)return;const w=srcCanvas.width,h=srcCanvas.height;const d=srcCanvas.getContext("2d").getImageData(0,0,w,h).data;const step=Math.max(3,Math.floor(Math.min(w,h)/350));let bestV={score:0,x:0},bestH={score:0,y:0};
  for(let x=Math.floor(w*.08);x<=Math.floor(w*.92);x+=step){let s=0,n=0;for(let y=Math.floor(h*.12);y<Math.floor(h*.88);y+=step){const i=(y*w+x)*4,ip=(y*w+Math.max(0,x-step))*4;s+=Math.abs(d[i]-d[ip])+Math.abs(d[i+1]-d[ip+1])+Math.abs(d[i+2]-d[ip+2]);n++}s/=n;if(s>bestV.score)bestV={score:s,x}}
  for(let y=Math.floor(h*.08);y<=Math.floor(h*.92);y+=step){let s=0,n=0;for(let x=Math.floor(w*.12);x<Math.floor(w*.88);x+=step){const i=(y*w+x)*4,ip=(Math.max(0,y-step)*w+x)*4;s+=Math.abs(d[i]-d[ip])+Math.abs(d[i+1]-d[ip+1])+Math.abs(d[i+2]-d[ip+2]);n++}s/=n;if(s>bestH.score)bestH={score:s,y}}
  // 保守預設：以影像中央的大框開始，避免智慧分析把白盒內容當成邊界。
  const x=w*.13,y=h*.09,r=w*.74,b=h*.82;frame={p:[{x,y},{x:x+r,y},{x:x+r,y:y+b},{x,y:y+b}]};draw();
}
$("smartBtn").onclick=()=>smartFrame();
$("resetBtn").onclick=()=>{if(srcCanvas){const w=srcCanvas.width,h=srcCanvas.height;frame={p:[{x:w*.12,y:h*.08},{x:w*.88,y:h*.08},{x:w*.88,y:h*.90},{x:w*.12,y:h*.90}]};draw()}};
function points(){return frame?.p||[]}
function pointer(e){const r=editor.getBoundingClientRect();return{x:(e.clientX-r.left)*editor.width/r.width,y:(e.clientY-r.top)*editor.height/r.height}}
function nearCorner(p){let best=-1,bd=Math.max(34,editor.width*.035);points().forEach((q,i)=>{const z=Math.hypot(p.x-q.x,p.y-q.y);if(z<bd){bd=z;best=i}});return best}
editor.addEventListener("pointerdown",e=>{const p=pointer(e);dragCorner=nearCorner(p);if(dragCorner>=0)editor.setPointerCapture(e.pointerId)});
editor.addEventListener("pointermove",e=>{if(dragCorner<0||!frame)return;const p=pointer(e),ps=frame.p;const min=28;ps[dragCorner].x=Math.max(min,Math.min(editor.width-min,p.x));ps[dragCorner].y=Math.max(min,Math.min(editor.height-min,p.y));draw()});
editor.addEventListener("pointerup",()=>dragCorner=-1);
function draw(){if(!srcCanvas||!frame)return;ctx.clearRect(0,0,editor.width,editor.height);ctx.drawImage(srcCanvas,0,0);ctx.save();ctx.fillStyle="rgba(0,0,0,.25)";ctx.fillRect(0,0,editor.width,editor.height);ctx.globalCompositeOperation="destination-out";ctx.beginPath();ctx.moveTo(frame.p[0].x,frame.p[0].y);frame.p.slice(1).forEach(q=>ctx.lineTo(q.x,q.y));ctx.closePath();ctx.fill();ctx.restore();ctx.save();ctx.strokeStyle="#2d72e8";ctx.lineWidth=Math.max(4,editor.width/260);ctx.beginPath();ctx.moveTo(frame.p[0].x,frame.p[0].y);frame.p.slice(1).forEach(q=>ctx.lineTo(q.x,q.y));ctx.closePath();ctx.stroke();frame.p.forEach(q=>{ctx.beginPath();ctx.fillStyle="#fff";ctx.strokeStyle="#2d72e8";ctx.lineWidth=4;ctx.arc(q.x,q.y,11,0,Math.PI*2);ctx.fill();ctx.stroke()});ctx.restore();processBtn.disabled=!files.length||!frame}

function loadImageCanvas(file,max=1800){return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{const s=Math.min(1,max/im.naturalWidth),c=document.createElement("canvas");c.width=Math.round(im.naturalWidth*s);c.height=Math.round(im.naturalHeight*s);c.getContext("2d").drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);resolve(c)};im.onerror=reject;im.src=u})}
function polygonMask(canvas,norm){const w=canvas.width,h=canvas.height,mask=new Uint8Array(w*h),p=norm.map(q=>({x:q.x*w,y:q.y*h}));const minX=Math.max(0,Math.floor(Math.min(...p.map(q=>q.x)))),maxX=Math.min(w-1,Math.ceil(Math.max(...p.map(q=>q.x)))),minY=Math.max(0,Math.floor(Math.min(...p.map(q=>q.y)))),maxY=Math.min(h-1,Math.ceil(Math.max(...p.map(q=>q.y))));function inside(x,y){let hit=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if(((a.y>y)!=(b.y>y))&&x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x)hit=!hit}return hit}for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++)if(inside(x+.5,y+.5))mask[y*w+x]=1;return{mask,p,minX,maxX,minY,maxY}}
function quadToNorm(){return frame.p.map(q=>({x:q.x/editor.width,y:q.y/editor.height}))}
async function processOne(file){const source=await loadImageCanvas(file),norm=quadToNorm(),m=polygonMask(source,norm),w=source.width,h=source.height,d=source.getContext("2d").getImageData(0,0,w,h).data;let x0=m.minX,y0=m.minY,x1=m.maxX,y1=m.maxY;const pad=.015,bw=x1-x0+1,bh=y1-y0+1;x0=Math.max(0,Math.floor(x0-bw*pad));y0=Math.max(0,Math.floor(y0-bh*pad));x1=Math.min(w-1,Math.ceil(x1+bw*pad));y1=Math.min(h-1,Math.ceil(y1+bh*pad));const cw=x1-x0+1,ch=y1-y0+1,size=+$('size').value,out=document.createElement('canvas');out.width=size;out.height=size;const c=out.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,size,size);const fit=Math.min(size*.84/cw,size*.84/ch),dw=cw*fit,dh=ch*fit,dx=(size-dw)/2,dy=(size-dh)/2;
  // 先產生「框內像素鎖定」圖層：框內原始像素完全不修改，框外透明。
  const layer=document.createElement('canvas');layer.width=cw;layer.height=ch;const lc=layer.getContext('2d'),ld=lc.createImageData(cw,ch);for(let yy=0;yy<ch;yy++)for(let xx=0;xx<cw;xx++){const sx=x0+xx,sy=y0+yy,si=(sy*w+sx)*4,li=(yy*cw+xx)*4;if(m.mask[sy*w+sx]){ld.data[li]=d[si];ld.data[li+1]=d[si+1];ld.data[li+2]=d[si+2];ld.data[li+3]=255}}
  lc.putImageData(ld,0,0);
  if($('shadow').checked){c.save();c.globalAlpha=.12;c.filter='blur(16px)';c.fillStyle='#000';c.beginPath();c.ellipse(size/2,dy+dh*.965,dw*.28,Math.max(7,dh*.018),0,0,Math.PI*2);c.fill();c.restore()}
  c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(layer,dx,dy,dw,dh);
  const type=$('format').value,blob=await new Promise((r,j)=>out.toBlob(b=>b?r(b):j(Error('輸出失敗')),type,type==='image/png'?undefined:.95));const ext=type==='image/png'?'png':type==='image/webp'?'webp':'jpg';return{name:file.name.replace(/\.[^.]+$/,'')+'_白底棚拍V11.'+ext,blob,url:URL.createObjectURL(blob),w:size,h:size}}

processBtn.onclick=async()=>{outputs=[];results.innerHTML='';progressWrap.classList.remove('hidden');processBtn.disabled=true;const start=Date.now();for(let i=0;i<files.length;i++){progressText.textContent=`正在處理 ${i+1}/${files.length}`;try{const o=await processOne(files[i]);outputs.push(o);render(o)}catch(e){render({name:files[i].name,error:'處理失敗：'+e.message})}const p=Math.round((i+1)/files.length*100);progressBar.style.width=p+'%';progressPct.textContent=p+'%';await new Promise(r=>setTimeout(r,10))}progressText.textContent='完成';processBtn.disabled=false;zipBtn.disabled=!outputs.length};
function render(o){const d=document.createElement('div');d.className='result';d.innerHTML=o.error?`<div class="result-name">${esc(o.name)}</div><div class="error">${esc(o.error)}</div>`:`<div class="preview-wrap"><img src="${o.url}"></div><div class="result-name">${esc(o.name)}</div><div class="result-meta">輸出 ${o.w} × ${o.h} px · ${(o.blob.size/1024).toFixed(0)} KB</div><span class="status">商品像素鎖定完成</span><br><a class="download" href="${o.url}" download="${esc(o.name)}">下載</a>`;results.appendChild(d)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
clearBtn.onclick=()=>{outputs.forEach(x=>x.url&&URL.revokeObjectURL(x.url));outputs=[];results.innerHTML='<div class="empty">尚無處理結果</div>';zipBtn.disabled=true}
zipBtn.onclick=async()=>{const z=await makeZip(outputs),u=URL.createObjectURL(z),a=document.createElement('a');a.href=u;a.download='商品白底棚拍V11_全部圖片.zip';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function makeZip(items){const enc=new TextEncoder(),parts=[],central=[];let off=0;for(const it of items){const n=enc.encode(it.name),data=new Uint8Array(await it.blob.arrayBuffer()),crc=crc32(data),l=new Uint8Array(30+n.length+data.length),v=new DataView(l.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,n.length,true);l.set(n,30);l.set(data,30+n.length);parts.push(l);const c=new Uint8Array(46+n.length),d=new DataView(c.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint32(16,crc,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,n.length,true);d.setUint32(42,off,true);c.set(n,46);central.push(c);off+=l.length}const cs=central.reduce((s,a)=>s+a.length,0),e=new Uint8Array(22),v=new DataView(e.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,items.length,true);v.setUint16(10,items.length,true);v.setUint32(12,cs,true);v.setUint32(16,off,true);return new Blob([...parts,...central,e],{type:'application/zip'})}
function crc32(b){let t=crc32.t;if(!t){t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}crc32.t=t}let c=0xffffffff;for(const x of b)c=t[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0}
