const $=id=>document.getElementById(id);
const fileInput=$("fileInput"),dropzone=$("dropzone"),fileStatus=$("fileStatus"),editor=$("editor"),ctx=editor.getContext("2d"),processBtn=$("processBtn"),zipBtn=$("zipBtn"),results=$("results"),clearBtn=$("clearBtn"),errorBox=$("error"),progressWrap=$("progressWrap"),progressBar=$("progressBar"),progressPct=$("progressPct"),progressText=$("progressText");
let files=[],outputs=[],srcCanvas=null,img=null,rect=null,dragCorner=-1;

fileInput.onchange=()=>setFiles([...fileInput.files]);
["dragover","dragenter"].forEach(e=>dropzone.addEventListener(e,x=>{x.preventDefault();dropzone.style.borderColor="#4c7fe8"}));
["dragleave","drop"].forEach(e=>dropzone.addEventListener(e,x=>{x.preventDefault();dropzone.style.borderColor="#cbd0d8"}));
dropzone.addEventListener("drop",e=>setFiles([...e.dataTransfer.files]));
function setFiles(arr){files=arr.filter(f=>/^image\/(jpeg|png|webp)$/.test(f.type));fileStatus.textContent=files.length?`已選取 ${files.length} 張圖片`:"未選取可處理的圖片";fileStatus.classList.toggle("ok",!!files.length);processBtn.disabled=!files.length||!rect;if(files.length)loadFirst(files[0])}
function loadFirst(f){const u=URL.createObjectURL(f);img=new Image();img.onload=()=>{const max=1400,s=Math.min(1,max/img.naturalWidth);srcCanvas=document.createElement("canvas");srcCanvas.width=Math.round(img.naturalWidth*s);srcCanvas.height=Math.round(img.naturalHeight*s);srcCanvas.getContext("2d").drawImage(img,0,0,srcCanvas.width,srcCanvas.height);editor.width=srcCanvas.width;editor.height=srcCanvas.height;smartRect();URL.revokeObjectURL(u)};img.src=u}
function smartRect(){if(!srcCanvas)return;const w=srcCanvas.width,h=srcCanvas.height,d=srcCanvas.getContext("2d").getImageData(0,0,w,h).data;let minX=w,minY=h,maxX=0,maxY=0,count=0;for(let y=Math.floor(h*.08);y<Math.floor(h*.9);y+=4){for(let x=Math.floor(w*.06);x<Math.floor(w*.94);x+=4){const i=(y*w+x)*4,r=d[i],g=d[i+1],b=d[i+2],v=(r+g+b)/3,s=Math.max(r,g,b)-Math.min(r,g,b);if(v>178&&s<48){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);count++}}}if(count<100){rect={x:w*.14,y:h*.10,w:w*.72,h:h*.78}}else{const pad=12;rect={x:Math.max(0,minX-pad),y:Math.max(0,minY-pad),w:Math.min(w-minX+pad*2,w),h:Math.min(h-minY+pad*2,h)};if(rect.w<w*.25||rect.h<h*.25)rect={x:w*.14,y:h*.10,w:w*.72,h:h*.78}}draw()}
$("smartBtn").onclick=()=>smartRect();$("resetBtn").onclick=()=>{if(srcCanvas){rect={x:srcCanvas.width*.12,y:srcCanvas.height*.08,w:srcCanvas.width*.76,h:srcCanvas.height*.82};draw()}};
function cp(p){return Math.max(0,Math.min(1,p))}
function points(){return[{x:rect.x,y:rect.y},{x:rect.x+rect.w,y:rect.y},{x:rect.x+rect.w,y:rect.y+rect.h},{x:rect.x,y:rect.y+rect.h}]}
function pointer(e){const r=editor.getBoundingClientRect();return{x:(e.clientX-r.left)*editor.width/r.width,y:(e.clientY-r.top)*editor.height/r.height}}
function nearCorner(p){const ps=points(),rad=Math.max(28,editor.width*.035);let best=-1,bd=rad;ps.forEach((q,i)=>{const z=Math.hypot(p.x-q.x,p.y-q.y);if(z<bd){bd=z;best=i}});return best}
editor.addEventListener("pointerdown",e=>{const p=pointer(e);dragCorner=nearCorner(p);if(dragCorner>=0)editor.setPointerCapture(e.pointerId)});
editor.addEventListener("pointermove",e=>{if(dragCorner<0)return;const p=pointer(e),min=30;if(dragCorner===0){const x=Math.min(p.x,rect.x+rect.w-min),y=Math.min(p.y,rect.y+rect.h-min);rect.w=rect.x+rect.w-x;rect.h=rect.y+rect.h-y;rect.x=x;rect.y=y}else if(dragCorner===1){const x=Math.max(p.x,rect.x+min),y=Math.min(p.y,rect.y+rect.h-min);rect.w=x-rect.x;rect.h=rect.y+rect.h-y;rect.y=y}else if(dragCorner===2){rect.w=Math.max(min,p.x-rect.x);rect.h=Math.max(min,p.y-rect.y)}else{const x=Math.min(p.x,rect.x+rect.w-min),y=Math.max(p.y,rect.y+min);rect.w=rect.x+rect.w-x;rect.h=y-rect.y;rect.x=x}draw()});
editor.addEventListener("pointerup",()=>dragCorner=-1);
function draw(){if(!srcCanvas||!rect)return;ctx.clearRect(0,0,editor.width,editor.height);ctx.drawImage(srcCanvas,0,0);ctx.save();ctx.fillStyle="rgba(0,0,0,.22)";ctx.fillRect(0,0,editor.width,editor.height);ctx.clearRect(rect.x,rect.y,rect.w,rect.h);ctx.strokeStyle="#2d72e8";ctx.lineWidth=Math.max(4,editor.width/260);ctx.strokeRect(rect.x,rect.y,rect.w,rect.h);points().forEach(p=>{ctx.beginPath();ctx.fillStyle="#fff";ctx.strokeStyle="#2d72e8";ctx.lineWidth=4;ctx.arc(p.x,p.y,11,0,Math.PI*2);ctx.fill();ctx.stroke()});ctx.restore();processBtn.disabled=!files.length||!rect}
$("threshold").oninput=e=>$("thresholdValue").textContent=e.target.value;

function cropCanvas(file){return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{const max=1800,s=Math.min(1,max/im.naturalWidth),c=document.createElement("canvas");c.width=Math.round(im.naturalWidth*s);c.height=Math.round(im.naturalHeight*s);c.getContext("2d").drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);resolve(c)};im.onerror=reject;im.src=u})}
function removeBackground(source,box,threshold){const w=source.width,h=source.height,s=source.getContext("2d").getImageData(0,0,w,h),d=s.data,mask=new Uint8Array(w*h);const x0=Math.max(0,Math.floor(box.x)),y0=Math.max(0,Math.floor(box.y)),x1=Math.min(w-1,Math.ceil(box.x+box.w)),y1=Math.min(h-1,Math.ceil(box.y+box.h));const q=[];const seen=new Uint8Array(w*h);
function idx(x,y){return y*w+x} function col(x,y){const i=idx(x,y)*4;return[d[i],d[i+1],d[i+2]]} function dist(a,b){return Math.sqrt((a[0]-b[0])**2+(a[1]-b[1])**2+(a[2]-b[2])**2)}
const seeds=[];for(let x=x0;x<=x1;x+=3){seeds.push([x,y0]);seeds.push([x,y1])}for(let y=y0;y<=y1;y+=3){seeds.push([x0,y]);seeds.push([x1,y])}
const avg=seeds.reduce((a,p)=>{const c=col(p[0],p[1]);return[a[0]+c[0],a[1]+c[1],a[2]+c[2]]},[0,0,0]).map(v=>v/seeds.length);
for(const [x,y] of seeds){const i=idx(x,y);if(!seen[i]){seen[i]=1;q.push([x,y,col(x,y)])}}
let head=0;while(head<q.length){const [x,y,base]=q[head++],i=idx(x,y);mask[i]=1;const ns=[[x+1,y],[x-1,y],[x,y+1],[x,y-1]];for(const [nx,ny] of ns){if(nx<x0||nx>x1||ny<y0||ny>y1)continue;const ni=idx(nx,ny);if(seen[ni])continue;const c=col(nx,ny);const db=dist(c,base),da=dist(c,avg);if(db<threshold*1.7&&da<threshold*2.2){seen[ni]=1;q.push([nx,ny,c])}}}
const out=source.getContext("2d").createImageData(w,h);for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const i=idx(x,y)*4;out.data[i]=d[i];out.data[i+1]=d[i+1];out.data[i+2]=d[i+2];out.data[i+3]=mask[idx(x,y)]?0:255}return{data:out,x0,y0,x1,y1}}
async function processOne(file){const source=await cropCanvas(file),sx=source.width/editor.width,sy=source.height/editor.height,box={x:rect.x*sx,y:rect.y*sy,w:rect.w*sx,h:rect.h*sy},thr=+$("threshold").value;const rm=removeBackground(source,box,thr),w=source.width,h=source.height;const bbox=getBBox(rm.data.data,w,h);if(!bbox)throw Error("找不到商品輪廓，請把框選範圍縮小後再試");let[x0,y0,x1,y1]=bbox,pad=.025,bw=x1-x0+1,bh=y1-y0+1;x0=Math.max(0,x0-bw*pad);y0=Math.max(0,y0-bh*pad);x1=Math.min(w-1,x1+bw*pad);y1=Math.min(h-1,y1+bh*pad);bw=x1-x0+1;bh=y1-y0+1;const size=+$("size").value,out=document.createElement("canvas");out.width=size;out.height=size;const c=out.getContext("2d");c.fillStyle="#fff";c.fillRect(0,0,size,size);const fit=Math.min(size*.84/bw,size*.84/bh),dw=bw*fit,dh=bh*fit,dx=(size-dw)/2,dy=(size-dh)/2;
const crop=document.createElement("canvas");crop.width=bw;crop.height=bh;const cc=crop.getContext("2d");const tmp=document.createElement("canvas");tmp.width=w;tmp.height=h;tmp.getContext("2d").putImageData(rm.data,0,0);cc.drawImage(tmp,x0,y0,bw,bh,0,0,bw,bh);
if($("shadow").checked){c.save();c.globalAlpha=.12;c.filter="blur(17px)";c.fillStyle="#000";c.beginPath();c.ellipse(size/2,dy+dh*.965,dw*.29,Math.max(7,dh*.018),0,0,Math.PI*2);c.fill();c.restore()}c.drawImage(crop,dx,dy,dw,dh);const type=$("format").value,blob=await new Promise((r,j)=>out.toBlob(b=>b?r(b):j(Error("輸出失敗")),type,type==="image/png"?undefined:.95));const ext=type==="image/png"?"png":type==="image/webp"?"webp":"jpg";return{name:file.name.replace(/\.[^.]+$/,"")+"_白底棚拍V10."+ext,blob,url:URL.createObjectURL(blob),w:size,h:size}}
function getBBox(data,w,h){let a=w,b=h,c=-1,d=-1;for(let y=0;y<h;y+=2)for(let x=0;x<w;x+=2)if(data[(y*w+x)*4+3]>0){a=Math.min(a,x);b=Math.min(b,y);c=Math.max(c,x);d=Math.max(d,y)}return c<0?null:[a,b,c,d]}
processBtn.onclick=async()=>{outputs=[];results.innerHTML="";progressWrap.classList.remove("hidden");processBtn.disabled=true;for(let i=0;i<files.length;i++){progressText.textContent=`正在處理 ${i+1}/${files.length}`;try{const o=await processOne(files[i]);outputs.push(o);render(o)}catch(e){render({name:files[i].name,error:"處理失敗："+e.message})}const p=Math.round((i+1)/files.length*100);progressBar.style.width=p+"%";progressPct.textContent=p+"%";await new Promise(r=>setTimeout(r,10))}progressText.textContent="完成";processBtn.disabled=false;zipBtn.disabled=!outputs.length}
function render(o){const d=document.createElement("div");d.className="result";d.innerHTML=o.error?`<div class="result-name">${esc(o.name)}</div><div class="error">${esc(o.error)}</div>`:`<div class="preview-wrap"><img src="${o.url}"></div><div class="result-name">${esc(o.name)}</div><div class="result-meta">輸出 ${o.w} × ${o.h} px · ${(o.blob.size/1024).toFixed(0)} KB</div><span class="status">商品保真處理完成</span><br><a class="download" href="${o.url}" download="${esc(o.name)}">下載</a>`;results.appendChild(d)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
clearBtn.onclick=()=>{outputs.forEach(x=>x.url&&URL.revokeObjectURL(x.url));outputs=[];results.innerHTML='<div class="empty">尚無處理結果</div>';zipBtn.disabled=true}
zipBtn.onclick=async()=>{const z=await makeZip(outputs),u=URL.createObjectURL(z),a=document.createElement("a");a.href=u;a.download="商品白底棚拍V10_全部圖片.zip";a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function makeZip(items){const enc=new TextEncoder(),parts=[],central=[];let off=0;for(const it of items){const n=enc.encode(it.name),data=new Uint8Array(await it.blob.arrayBuffer()),crc=crc32(data),l=new Uint8Array(30+n.length+data.length),v=new DataView(l.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,n.length,true);l.set(n,30);l.set(data,30+n.length);parts.push(l);const c=new Uint8Array(46+n.length),d=new DataView(c.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint32(16,crc,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,n.length,true);d.setUint32(42,off,true);c.set(n,46);central.push(c);off+=l.length}const cs=central.reduce((s,a)=>s+a.length,0),e=new Uint8Array(22),v=new DataView(e.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,items.length,true);v.setUint16(10,items.length,true);v.setUint32(12,cs,true);v.setUint32(16,off,true);return new Blob([...parts,...central,e],{type:"application/zip"})}
function crc32(b){let t=crc32.t;if(!t){t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}crc32.t=t}let c=0xffffffff;for(const x of b)c=t[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0}
